### PR TITLE
Enhancement user request changes

### PR DESCRIPTION
**Pull request by Lopesh**
**Trello Tickets: **
https://trello.com/c/WPlWP1FQ/207-remove-some-emails
https://trello.com/c/mNWEduTo/210-remove-sameertjoshsoftwarecom-from-time-sheets-reminder-mails

### CODE REVIEW

**Comment by Lopesh** [comment]
[remove sameert@joshsoftware.com from time sheets reminder mails](https://trello.com/c/mNWEduTo/210-remove-sameertjoshsoftwarecom-from-time-sheets-reminder-mails)

**Comment by Lopesh** [comment]
[Remove some emails](https://trello.com/c/WPlWP1FQ/207-remove-some-emails)

**Comment by RohitNalePUCSD** [comment]
Sameer mail id ("sameer@joshsoftware.com") does not include in all timesheet emails. His email id includes only those employees whose manager is Sameer.

**Comment by RohitNalePUCSD** [comment]
Sameer mail id ("sameer@joshsoftware.com") does not include in all timesheet emails. His email id includes only those employees whose manager is Sameer.

**Pull request closed without merging**
